version: "3"

services:
  rasa:
    image: jaimeteb/02_pokebot:latest
    env_file: .env
    volumes:
      - models:/app/models
    ports:
      - "5002:5002"
      - "5005:5005"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 800M

volumes:
  models:
